In [1]:
import tensorflow as tf 
import numpy as np


2024-06-01 03:29:01.489086: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-01 03:29:01.493278: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-01 03:29:01.538120: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-01 03:29:02.601242: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
#scalar tensor
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
#rank1 tensor - vector
rank_1_tensor = tf.constant([1,2,3,4])
print(rank_1_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [4]:
#rank2 tensor = matrix
rank_2_tensor = tf.constant([[1,2],
[3,4], [5,6]])
print(rank_2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [5]:
#rank3 tensor = tensor
rank_3_tensor = tf.constant([
    [[0,1,2,3,4], [5,6,7,8,9]],

    [[10,11,12,13,14], [15,16,17,18,19]],
    
    [[20,21,22,23,24], [25,26,27,28,29]],
    ])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [6]:
numper = np.array(rank_2_tensor)
print(numper)
print(rank_2_tensor)
print(numper==rank_2_tensor)

[[1 2]
 [3 4]
 [5 6]]
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ True  True]
 [ True  True]
 [ True  True]], shape=(3, 2), dtype=bool)


In [7]:
#raggedtensor and sparse sensor exist too!!

#now tensor math!

a = tf.constant([
    [1,2],
    [3,4]
])
b = tf.ones([2,2], dtype=tf.int32)

print(tf.add(a,b), "\n") 
print(tf.multiply(a,b), "\n") #elementiwse
print(tf.matmul(a,b), "\n")
print()
print(a+b)
print(a*b)
print(a@b)


tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 


tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [8]:
#additional operations
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

print(tf.reduce_max(c))
print(tf.math.argmax(c))
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [9]:
#shape = length of num of elements on each axes
#rank = num of tensor axes
#axis = particular dim of tensor
#size = total num of elements in the sensor

#rank 4 tensor = think bundle of tensors like group by
#highlight of a total tensor

rank_4_tensor = tf.zeros([3,2,4,5], dtype=tf.int32) #3 vertical groups,
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy()) 

#in this case we have 4 possible tensor axis given rank 4
# 3 blocks, each block is h x w x l = 2 x 4 x 5 or in other words
# 3 different double layer 4x5 matrices

Type of every element: <dtype: 'int32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


In [13]:
#multilevel indexing
print(rank_2_tensor)
print()
print(rank_2_tensor[1,1].numpy())
print()
print(rank_2_tensor[0,0].numpy())

print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

4

1
Second row: [3 4]
Second column: [2 4 6]
Last row: [5 6]
First item in last column: 2
Skip the first row:
[[3 4]
 [5 6]] 



In [16]:
#flattening a tensor
print(rank_3_tensor)
print(tf.reshape(rank_3_tensor, [-1])) #flatten to list
print(tf.reshape(rank_3_tensor, [3*2,5])) #goes to a (3*2) x 5

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)
tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


In [17]:
#dont reshape with axis changes use transpose
#ragged tensors - tensor with variable number of elements
#along some axis

ragged_list = [
    [1,2,3,4],
    [5,6],
    [7],
    [8,9,10,11]
]

ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[1, 2, 3, 4], [5, 6], [7], [8, 9, 10, 11]]>


In [19]:
#string tensors
scalar_string_tensor = tf.constant("gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'gray wolf', shape=(), dtype=string)


In [21]:
print(tf.strings.split(scalar_string_tensor, sep=' '))
print(tf.strings.split(tf.strings.split(scalar_string_tensor, sep=' ')))

tf.Tensor([b'gray' b'wolf'], shape=(2,), dtype=string)
<tf.RaggedTensor [[b'gray'],
 [b'wolf']]>


In [25]:
#sparse tensor
sparse_tensor = tf.sparse.SparseTensor(indices=[[0,0], [1,2]], values=[1,2], dense_shape=[3,4])
print(sparse_tensor)
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
